name: Release

on:
  release:
    types: [published]

jobs:
  release_ip2location:
    name: Release IP2Location
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0

    - name: Unzip
      run: |
        unzip IP2LOCATION-LITE-DB11.BIN.ZIP
        unzip IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP

    - name: Upload release asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.YOURTOKEN }}
        file: ./IP2LOCATION-LITE-*.BIN/IP2LOCATION-LITE-*.BIN
        tag: ${{ github.ref }}
        file_glob: true