name: Renew

on:
  workflow_dispatch:
  schedule:
    - cron: 0 9 1 * *

permissions:
  contents: write

jobs:
  renew:
    name: Renew
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Download
        run: |
          echo "NOW=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
          wget "https://www.ip2location.com/download/?token=${{ secrets.IP2LOCATION_TOKEN }}&file=DB11LITEBIN" -O ./IP2LOCATION-LITE-DB11.BIN.ZIP
          wget "https://www.ip2location.com/download/?token=${{ secrets.IP2LOCATION_TOKEN }}&file=DB11LITEBINIPV6" -O ./IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP

      - name: Unzip
        run: |
          mkdir ./BIN
          unzip -o IP2LOCATION-LITE-DB11.BIN.ZIP -d ./BIN
          unzip -o IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP -d ./BIN

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ env.NOW }}
          prerelease: false
          title: ${{ env.NOW }}
          files: |
            ./BIN/*.BIN
