name: Renew

on:
  schedule:
    - cron: 0 9 1 * *

jobs:
  renew:
    name: Renew
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/checkout@v2
        run: |
          echo "::set-env name=NOW::$(date +'%Y.%m.%d')"
          wget https://www.ip2location.com/download/?token=${{ secrets.IP2LOCATION_TOKEN }}&file=DB11LITEBIN
          wget https://www.ip2location.com/download/?token=${{ secrets.IP2LOCATION_TOKEN }}&file=DB11LITEBINIPV6

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Renew Database
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@renfei.net
          commit_author: github-actions[bot] <github-actions[bot]@renfei.net>
          tagging_message: ${{ env.NOW }}

      - name: Unzip
        run: |
          mkdir ./BIN
          unzip -o IP2LOCATION-LITE-DB11.BIN.ZIP -d ./BIN
          unzip -o IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP -d ./BIN

      - name: Release
        use: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.YOURTOKEN }}
          automatic_release_tag: ${{ env.NOW }}
          prerelease: true
          title: ${{ env.NOW }}
          files: ./BIN/*.BIN